### ISSUE TITLE
mermaid model bold title

### ISSUE THREAD

**Issue by Kodzhabashev** [humdek-unibe-ch/sh-selfhelp#188]
In GitLab by @ingridodermatt on Sep 12, 2019, 11:06

Is it possible to make the titles of the inputs in the mermaid model bold? It would be easier to distinguish it from the input/textareas.

**Comment by Kodzhabashev** [comment]
In GitLab by @moiri on Sep 12, 2019, 14:13

Unfortunately, this is not possible with the current solution.

With some rather nasty workarounds it might be possible to add a divider between the title and the content: ![Screenshot_from_2019-09-12_14-02-40](http://phhum-a209-cp.unibe.ch:10012/SLP/SLP-sleep_coach/uploads/416a9c9a0aa882ba4cf2173185ceac62/Screenshot_from_2019-09-12_14-02-40.png)

But this would have to wait for a new release in the future.

Alternatively you could just add a special symbol like a `*` or a `#` to distinguish the title from the content.

**Comment by Kodzhabashev** [comment]
In GitLab by @ingridodermatt on Sep 12, 2019, 14:20

okay thanks!
The divider looks nice but as it is not that crucial, I don't think it is worth to spend time for that! Most important is that the title stays there :)

**Comment by Kodzhabashev** [comment]
In GitLab by @ingridodermatt on Sep 12, 2019, 14:20

closed

**Comment by Kodzhabashev** [comment]
In GitLab by @moiri on Sep 12, 2019, 14:46

We just came up with a thing that you could do on your own with css rules:

```css
.mermaidForm * .pointer * div::after {
    position: absolute;
    top: 1.75rem;
    left: 0;
    content: '';
    background-color: rgba(0,0,0,.1);
    height: 1px;
    width: 100%;
}
```

The above would add a divider for each mermaid field that is editable.
You could also address individual fields by using a corresponding id selector.
