### ISSUE TITLE
change color of navigation menu / progress bar

### ISSUE THREAD

**Issue by Kodzhabashev** [humdek-unibe-ch/sh-selfhelp#205]
In GitLab by @ingridodermatt on Oct 28, 2019, 09:38

Is there a way to change the color of the navigation menu and navigation buttons?

And how can I change the color of the progress bar to a customized color (not one of the predefined styles)? I only managed to change the grey right part of the bar, but I would like to change the left part.

**Comment by Kodzhabashev** [comment]
In GitLab by @moiri on Oct 29, 2019, 10:38

To do such customizations you need to create a custom *.css file (you can upload these over the menu Admin->Assets in the card "User-defined CSS Files").

To change the background color of the navbar you need a CSS rule similar to this:
```css
.navbar {
    background-color: #ff0000 !important;
}
```
If you want to change the font color in the navbar you need to add several rules:
```css
.navbar > .navbar-brand {
    color: #00ff00;
}

.navbar > .navbar-brand:hover {
    color: #000000;
}

.navbar * .nav-link {
    color: #00ff00 !important;
}

.navbar * .nav-link:hover {
    color: #000000 !important;
}

.navbar * .nav-link.active {
    color: #0000ff !important;
}
```

To change the color of the progress bar you need to select the type `none` and add a custom class (in my example `custom-progress`) to the progress style in question. Then add the following CSS rule to the custom css file:
```css
.custom-progress > .progress-bar {
    background-color: #ff0000;
}
```

If a type is selected (e.g. primary) you need to add `!important` to your CSS rule.

Alternatively if you want to overwrite an existing progress type (say info) you can use the following CSS rule:
```css
.progress > .progress-bar.bg-info {
    background-color: #0000ff !important;
}
```

A side note: I chose these horrendous colors to better illustrate which CSS rule affects which item.

**Comment by Kodzhabashev** [comment]
In GitLab by @ingridodermatt on Oct 29, 2019, 16:25

Thanks for the answer and the illustration! For the progress bar it works perfectly!

I meant the navigation menu and buttons of a navigation page (so the menu that is shown on the left side of a navigation page and the buttons at the bottom of the page (that are refering to the previous and the next navigation container). They are in the primary style. 
I tried to adjust it from your explanation but I have not managed yet.

**Comment by Kodzhabashev** [comment]
In GitLab by @moiri on Oct 29, 2019, 17:16

Ok, for the navigation of navigation pages you need to assign a custom css class to the nav menu (you can do this by adding a class name to the field `css_nav` of the navigation page).

You can then use this custom class to specify changes on one specific nav menu (I used the cutom css class `my-nav`):
```css
.my-nav * .nested-list-item-name.active {
    background-color: #ff0000;
}

.my-nav * .nested-list-item-name.active:hover {
    background-color: #00ff00;
}

.my-nav * .nested-list-item-name {
    color: #0000ff;
}

.my-nav * .nested-list-item-name:hover {
    color: #000000;
}
```

If you wish to overwrite the color of all navigation menus you can use the class name `nested-list` instead of `my-nav`.
